version: '3.8'

services:
  user-service:
    build: .
    container_name: user-service
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - user-mongo

  user-mongo:
    image: mongo:6
    container_name: user-mongo
    ports:
      - "27017:27017"
    volumes:
      - user-mongo-data:/data/db

volumes:
  user-mongo-data:
